name: Deploy

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PK }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.SSH_USER}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

            # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ahmeddapo0110/repos
              rm -rf website
              gh repo clone Theraswift-Technology/website
              cd website
              git checkout main  
              node -v
              npm i && echo INSTALLED DEPENDENCIES
              npm run build && echo BUILT CODE
              sudo rm -rf /var/www/theraswift.io &&  echo  REMOVED DIST DIRECTORY
              sudo mkdir -p /var/www/theraswift.io/dist &&  echo  MADE DIST DIRECTORY
              sudo mv -f dist /var/www/theraswift.io &&  echo  MOVED BUILT CODE
              sudo mv -f node_modules /var/www/theraswift.io/dist && echo MOVED DEPENDENCIES
              sudo cp serverconf/default.conf /etc/nginx/sites-available/theraswift.io && echo Copied Server Conf
              sudo ln -s /etc/nginx/sites-available/theraswift.io /etc/nginx/sites-enabled/ && echo Linked Server Conf
              exit
              '
